### ISSUE TITLE
GitHub Actions for automated pkg builds of Nudge

### ISSUE THREAD

**Issue by erikng** [erikng/NudgeSwift#49]
I want GitHub Actions to build packages (not dmgs) of Nudge

1. We need a signing certificate for the app. I'm hoping @natewalck will create one for us
2. We need a pkg signing certificate. @natewalck - again, can I use the one we already use for macadmins/python

This will then allow us to make an autopkg recipe so people can quickly deploy new versions. I prefer pkgs over dmgs as it's one less step for non-munki tooling

I've never done automated `xcbuild` stuff so hoping someone else might already know what to do.

**Comment by rorymurdock** [comment]
Once we write Unit/UI tests
`xcodebuild clean test -target Nudge -scheme Nudge`

Building the app
`xcodebuild -target Nudge -scheme Nudge`
Outputs the artifact to `./NudgeSwift/build/Release/Nudge.app`

Once we get nate's certs we can test it.

Extra reading
- https://rhonabwy.com/2020/05/09/continuous-integration-with-github-actions-for-macos-and-ios-projects/
- https://medium.com/@karaiskc/archive-and-export-ios-app-with-github-actions-b44f676e4bf9

**Comment by erikng** [comment]
Before we can do this, we need to complete https://github.com/erikng/NudgeSwift/issues/50

**Comment by erikng** [comment]
Well I forgot about https://github.com/erikng/NudgeSwift/issues/50 but worst case is I just re-setup the secrets.

https://github.com/erikng/NudgeSwift/releases/tag/v.0.0.2.02112021052021
