### ISSUE TITLE
Sign application and sign/notarize pkg

### ISSUE THREAD

**Issue by erikng** [erikng/NudgeSwift#53]

**Comment by erikng** [comment]
It took me 10 commits but: https://github.com/erikng/NudgeSwift/releases/tag/v.0.0.2.02112021052021

**Comment by rorymurdock** [comment]
I want to update the yml to use something like the tag as the release version because currently it's staticly coded in.

**Comment by erikng** [comment]
That bothered me too. I've now fixed it.
